# Generated by Django 3.2.16 on 2023-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('Job_Description', models.CharField(max_length=400)),
                ('Responsibilities', models.CharField(max_length=400)),
                ('Requirements', models.CharField(max_length=400)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('WEBDEV', 'Web Development'), ('LEADERSHIP', 'Leadership'), ('WEBAPP', 'Web Application'), ('APPDEPLOY', 'Application Deployment')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_path1', models.CharField(max_length=300)),
                ('image_path2', models.CharField(max_length=300)),
                ('image_path3', models.CharField(max_length=300)),
                ('image_path4', models.CharField(max_length=300)),
                ('image_path5', models.CharField(max_length=300)),
                ('des', models.TextField(max_length=1000)),
            ],
        ),
    ]
